export const FETCH_DATA_BEGIN = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_ALL_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_ONE_PRODUCT_SUCCESS = 'FETCH_PRODUCTS_ITEM_SUCCESS';
export const FETCH_DATA_END = 'FETCH_PRODUCTS_END';
export const SORT_NAME_VALUE = `SORT_NAME_VALUE`;
